# Generated by Django 3.2.2 on 2023-11-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_log_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
